apiVersion: uptest.upbound.io/v1beta1
kind: TestSuite
metadata:
  name: provider-backblaze-test-suite
spec:
  # Maximum time to wait for a test to complete
  timeout: 1800s
  # Maximum time to wait for a resource to become ready
  readyTimeout: 900s
  # Maximum time to wait for a resource to be deleted
  deleteTimeout: 900s
  # Skip resource deletion after test completion (useful for debugging)
  skipDelete: false
  # Directory containing test manifests
  testDir: examples
  # Setup script to run before tests
  setupScript: cluster/test/setup.sh
  # Teardown script to run after tests
  teardownScript: cluster/test/cleanup.sh
  # Default conditions to wait for
  defaultConditions:
    - Ready
    - Synced
  # Tests to run
  tests:
    - name: bucket
      manifest: examples/bucket/bucket.yaml
      timeout: 900s
      conditions:
        - Ready
        - Synced
    - name: applicationkey
      manifest: examples/applicationkey/applicationkey.yaml
      timeout: 900s
      conditions:
        - Ready
        - Synced
      depends:
        - bucket
  # Resource cleanup order (most dependent first)
  cleanup:
    - applicationkey
    - bucket